# Generated by Django 5.1.14 on 2026-02-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0063_alter_botchatmessagerequest_to'),
        ('bots', '0075_alter_botmediarequest_loop'),
    ]

    operations = [
    ]
