# Generated by Django 5.1.14 on 2026-02-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0076_merge_20260205_0000'),
        ('bots', '0077_alter_participantevent_event_type_and_more'),
    ]

    operations = [
    ]
